Controllers/ClassController.cs
using StudentManage.Models;
using StudentManage.Sevices.Interface;
using StudentManage.Sevices.Repo;
using StudentManage.ViewModels.ClassViewModels;
using StudentManage.ViewModels.StudentViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentManage.Controllers
{
    public class ClassController : Controller
    {
        // GET: AllClass
        private IClass classService = new ClassRepo();
        private IStudentOfClass studentOfClass = new StudentOfClassRepo();
        private ITeacher teacherService = new TeacherRepo();
        public ActionResult Index()
        {
            var listClass = classService.GetAllClass();
            return View(listClass);
        }

        [HttpGet]
        public ActionResult Create()
        {
            CreateClass creates = new CreateClass()
            {
                Teachers = teacherService.GetAllTeacher()
            };
            return View(creates);
        }

        [HttpPost]
        public ActionResult Create(CreateClass model)
        {

            if (ModelState.IsValid)
            {

                if (classService.CheckMa(model.MaClass))
                {
                    ModelState.AddModelError("MaClass", "Mã Này Đã Tồn Tại");
                    model.Teachers = teacherService.GetAllTeacher();
                    return View(model);
                }

                if (classService.CheckTeacher(model.TeacherID) >= 5)
                {
                    ModelState.AddModelError("TeacherID", "Giáo viên này đã nhận đủ lớp");
                    model.Teachers = teacherService.GetAllTeacher();
                    return View(model);
                }
                Class classes = new Class()
                {
                    MaClass = model.MaClass,
                    NameClass = model.NameClass,
                    TeacherID = model.TeacherID
                };
                classService.Insert(classes);
                classService.Save();

            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
           
            Class clas = classService.GetByID(id);
            if(clas is null)
            {
                return HttpNotFound();
            }
            EditClass editClas = new EditClass()
            {
                ID = clas.ID,
                MaClass = clas.MaClass,
                NameClass = clas.NameClass,
                Teachers = teacherService.GetAllTeacher(),
                TeacherID = clas.TeacherID

            };
            return View(editClas);
        }

        [HttpPost]
        public ActionResult Edit(EditClass model)
        {
            
            classService.UpdateClass(model);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Detail(int Id)
        {
            Class detailList = classService.GetByID(Id);
            if(detailList is null)
            {
                return HttpNotFound();
            }
            Detaill details = new Detaill()
            {
                MaClass = detailList.MaClass,
                NameClass = detailList.NameClass,
                NameTeacher = detailList.Teacher.NameTeacher
            };
            return View(details);

        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {
            string messenger = "";
            bool succes = default;
            Class getIdClass = classService.GetByID(Id); 
            if(getIdClass is null)
            {
                messenger = "ID Không Tồn Tại";
                succes = false;
            }
            //if(getIdClass.TeacherID > 0)
            //{
            //    messenger = "Không Thể Xóa Sinh Viên Đang Tồn Tại";
            //    succes = false;
            //}
            else
            {
                classService.Delete(Id);
                messenger = "Xóa Thành Công";
                succes = true;
            }

            return Json(new { mess = messenger, suc = succes }, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Class/Create.cshtml
@model StudentManage.ViewModels.ClassViewModels.CreateClass

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Class</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaClass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaClass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaClass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameClass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameClass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameClass, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <label class=" control-label col-md-2">Chọn Giáo Viên</label>
            <select name="TeacherID" id="TeacherID" class="form-control">
                <option selected>---Vui Lòng Chọn Giáo Viên---</option>
                @foreach (var itemtea in Model.Teachers)
                {
                    <option value="@itemtea.ID">@itemtea.NameTeacher</option>
                }

            </select>
            @Html.ValidationMessageFor(model => model.TeacherID, "", new { @class = "text-danger" })

        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Class/Detail.cshtml
@model StudentManage.ViewModels.ClassViewModels.Detaill

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detail</h2>

<div>
    <h4>Detaill</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaClass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaClass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameClass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameClass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameTeacher)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameTeacher)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Class/Edit.cshtml
@model StudentManage.ViewModels.ClassViewModels.EditClass

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>EditClass</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.MaClass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaClass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaClass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameClass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameClass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameClass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeacherID, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.TeacherID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Chọn Giáo Viên </label>
            <select name="TeacherID" id="TeacherID" class="form-control">
                <option selected> --- Vui Lòng Chọn Khoa ---</option>
                @foreach (var itemTea in Model.Teachers)
                {
                    var select = itemTea.ID == Model.TeacherID ? "selected" : string.Empty;
                    <option value="@itemTea.ID" @select>@itemTea.NameTeacher</option>
                }
            </select>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Class/Index.cshtml
@model IEnumerable<StudentManage.Models.Class>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h2>Danh Sách Lớp</h2>
    <a class="btn btn-success" href="/Class/Create">Thêm Lớp</a>
    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th style="width: 10%">Mã Lớp</th>
                <th style="width: 20%">Tên Lớp</th>
                <th style="width: 20%">GVCN</th>
                <th style="width: 50%">Action</th>
            </tr>
        </thead>

        <tbody>
            @if (Model.Count() >= 0)
            {
                foreach (var itemc in Model)
                {
                    <tr>
                        <td> @itemc.MaClass</td>
                        <td>@itemc.NameClass</td>
                        <td>@itemc.Teacher.NameTeacher</td>
                        <td>
                            <a class="btn btn-info" href="Class/Edit/@itemc.ID">Sửa</a>
                            <a class="btn btn-warning" href="Class/Detail/@itemc.ID">Chi Tiết</a>
                            <a class="btn btn-danger btnDlete" data-id="@itemc.ID" >Xóa</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</body>
</html>

@section Scripts{
    <script type="text/javascript">
        $('.btnDlete').click(function () {
            var id = $(this).attr("data-id");
            var tb = confirm("Bạn có chắc muốn xóa");
            if (tb) {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Delete","Class")",
                    data: {
                        Id: id
                    }

                }).done(function (reponse) {
                    if (reponse.suc) {
                        alert(reponse.mess);
                        location.reload();
                    } else {
                        alert(reponse.mess);
                    }
                }).fail(function () {
                    alert("ERROR, Vui lòng quay lại sau")
                })
            } 
        });
    </script>
}