Models/Year.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Year
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Year()
        {
            this.StudentJoinYears = new HashSet<StudentJoinYear>();
        }
    
        public int ID { get; set; }
        public string Year_Code { get; set; }
        public string Year_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentJoinYear> StudentJoinYears { get; set; }
    }
}

ViewModels/YearViewModel/YearViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StudentManage.ViewModels.YearViewModel
{
    public class CreateYear
    {
        [Required(ErrorMessage ="Vui long nhap ma nam")]
        [MaxLength(5,ErrorMessage ="Ma nam khong qua 5 ki tu")]
        public string Year_Code { get; set; }
        [Required(ErrorMessage = "Vui long nhap ten nam")]
        [MaxLength(50, ErrorMessage = "Ten nam khong qua 50 ki tu")]
        public string Year_Name { get; set; }
    }

    public class EditYear : CreateYear
    {
        public int ID { get; set; }
    }

    public class Details : CreateYear
    {
        public int ID { get; set; }
    }
}

Controllers/YearController.cs
using StudentManage.Models;
using StudentManage.Sevices.Interface;
using StudentManage.Sevices.Repo;
using StudentManage.ViewModels.YearViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentManage.Controllers
{
    public class YearController : Controller
    {
        // GET: Year
        private IYear yearService = new YearRepo();
        public ActionResult Index()
        {
            var listKhoa = yearService.GetAll();
            return View(listKhoa);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CreateYear modelyear)
        {
            if (yearService.CheckYearCode(modelyear.Year_Code))
            {
                ModelState.AddModelError("Year_Code", "Mã này đã tồn tại");
                return View(modelyear);
            };
            if (ModelState.IsValid)
            {
                Year year = new Year()
                {
                    Year_Code = modelyear.Year_Code,
                    Year_Name = modelyear.Year_Name
                };
                yearService.Insert(year);
                yearService.Save();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            Year year = yearService.GetByID(Id);
            if (year is null)
            {
                return HttpNotFound();
            }
            EditYear eyear = new EditYear()
            {
                Year_Code = year.Year_Code,
                Year_Name = year.Year_Name
            };
            return View(eyear);
        }

        [HttpPost]
        public ActionResult Edit(EditYear modelYear)
        {
            if (ModelState.IsValid)
            {
                Year year = new Year()
                {
                    ID = modelYear.ID,
                    Year_Code = modelYear.Year_Code,
                    Year_Name = modelYear.Year_Name
                };
                yearService.Update(year);
                yearService.Save();
                return RedirectToAction("Index");
            }
            return View(modelYear);
        }

        [HttpGet]
        public ActionResult Detail(int Id)
        {
            Year year = yearService.GetByID(Id);
            if (year is null)
            {
                return HttpNotFound();
            }
            Details detailsYear = new Details()
            {
                ID = year.ID,
                Year_Code = year.Year_Code,
                Year_Name = year.Year_Name
            };
            return View(detailsYear);
        }

        //[HttpPost]
        //public ActionResult Delete(int Id)
        //{
        //    Year year = yearService.GetByID(Id);
        //    if(year is null)
        //    {
        //        return HttpNotFound();
        //    }
        //    yearService.Delete(year);
        //    yearService.Save();
        //    return RedirectToAction("Index");
        //}

        ///ajax
        [HttpPost]
        public ActionResult Delete(int Id)
        {
            string messenge = "";
            bool success = default;
            Year year = yearService.GetByID(Id);
            if (year is null)
            {
                messenge = "Id Bạn Tìm Không Tồn Tại";
                success = false;
            }
            if (year.StudentJoinYears.Count > 0)
            {
                messenge = "Không Thể Xóa Sinh Viên Đã Tồn Tại";
                success = false;
            }
            else
            {
                messenge = "Xóa Thành Công !";
                success = true;
                yearService.Delete(year);
                yearService.Save();
            }

            return Json(new { messenge = messenge, success = success }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult DeleteYearCode(string yearCode)
        {
            string messenge = "";
            bool success = default;
           
                messenge = "Xóa Thành Công !";
                success = true;

                yearService.DeleteYearCode(yearCode);
           
           

            return Json(new { messenge = messenge, success = success }, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Year/Create.cshtml
@model StudentManage.ViewModels.YearViewModel.CreateYear

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CreateYear</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Year_Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year_Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year_Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Year/Detail.cshtml
@model StudentManage.ViewModels.YearViewModel.Details

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detail</h2>

<div>
    <h4>EditYear</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Year_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year_Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year_Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { Id = Model.ID}) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Year/Edit.cshtml
@model StudentManage.ViewModels.YearViewModel.EditYear

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EditYear</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Year_Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year_Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year_Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Year_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Year_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Year/Index.cshtml
@model IEnumerable<StudentManage.Models.Year>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="https://cdn.jsdelivr.net/npm/sweetalert2@9.17.1/dist/sweetalert2.min.css" rel="stylesheet">

<h2>Danh sach nam hoc</h2>

<style>
    #bot {
        margin-bottom: 10px;
    }
</style>

<a href="/Year/Create" class="btn btn-success" id="bot">Them Nam</a>

<table class="table table-dark table-striped">
    <thead>
        <tr>

            <th style="width: 30%">Ma Nam</th>
            <th style="width: 50%">Nam Hoc</th>
            <th style="width: 20%">Action</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() >= 0)
        {
            foreach (var itemy in Model)
            {
                <tr>

                    <td>@itemy.Year_Code</td>
                    <td>@itemy.Year_Name</td>
                    <td>
                        <a class="btn btn-info" href="Year/Edit/@itemy.ID">Sửa</a>
                        <a class="btn btn-warning" href="Year/Detail/@itemy.ID">Chi Tiết</a>

                        @*@using (Html.BeginForm("Delete", "Year", new { Id = itemy.ID}, FormMethod.Post))
        {
            <button class="btn btn-danger" data-id="@itemy.ID">Xóa</button>
        }*@
                        <button class="btn btn-danger btnDelete" data-id="@itemy.ID">Xóa</button>
                        <button class="btn btn-success btnDeleteY" data-string="@itemy.Year_Code">Xóa Theo Year Code</button>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>
@section Scripts{
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9.17.1/dist/sweetalert2.min.js"></script>
    <script type="text/javascript">
        $('.btnDelete').click(function () {
            var id = $(this).attr("data-id");
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        type: "POST",
                        url: "@Url.Action("Delete","Year")",
                        data: {
                            Id: id
                        }
                    }).done(function (reponse) {
                        if (reponse.success) {
                            Swal.fire(
                                'Deleted!',
                                reponse.messenge,
                                'success'
                            )
                            location.reload();
                        } else {
                            Swal.fire(reponse.messenge);
                        }
                    }).fail(function () {
                        alert("ERROR, Vui lòng quay lại sau");
                    })
                }
            })

        })

          $('.btnDeleteY').click(function () {
            var yearCodee = $(this).attr("data-string");
            var tb = confirm("Bạn có muốn xóa");
            if (tb) {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("DeleteYearCode", "Year")",
                    data: {
                        yearCode: yearCodee
                    }
                }).done(function (reponse) {
                    if (reponse.success) {
                        alert(reponse.messenge);
                        location.reload();
                    }
                       // else {
                    //    alert(reponse.messenge);
                    //}

                }).fail(function () {
                    alert("ERROR, Vui lòng quay lại sau")
                })
            }

        });
    </script>
}