Models/Khoa.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Khoa()
        {
            this.StudentOfKhoas = new HashSet<StudentOfKhoa>();
        }
    
        public int ID { get; set; }
        public string Khoa_Code { get; set; }
        public string Khoa_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentOfKhoa> StudentOfKhoas { get; set; }
    }
}

ViewModels/KhoaViewModel/KhoaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StudentManage.ViewModels.KhoaViewModel
{
    public class CreateKhoa
    {
        [Required(ErrorMessage = "Vui Long Nhap Ma Khoa")]
        [MaxLength(5, ErrorMessage = "Ma khoa khong duoc qua 5 ki tu")]
        public string Khoa_Code { get; set; }
        [Required(ErrorMessage = "Vui Long Nhap Ten Khoa")]
        [MaxLength(50, ErrorMessage = "Ten khoa khong duoc dai hon 50 ki tu")]
        public string Khoa_Name { get; set; }
    }

    public class EditKhoa : CreateKhoa
    {
        [Required]
        public int ID { get; set; }
    }

    public class Details : CreateKhoa
        {
        public int ID { get; set; }
        }
}

Controllers/KhoaController.cs
using StudentManage.Models;
using StudentManage.Sevices.Interface;
using StudentManage.Sevices.Repo;
using StudentManage.ViewModels.KhoaViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StudentManage.Controllers
{
    public class KhoaController : Controller
    {
        private IKhoa khoaService = new KhoaRepo();
        //private object listKhoa;

        //private object listKhoa;

        //private object khoa;

        // GET: Khoa
        public ActionResult Index()
        {
            var listKhoa = khoaService.GetAll();
            return View(listKhoa);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CreateKhoa model)
        {
            if (khoaService.CheckCode(model.Khoa_Code))
            {
                ModelState.AddModelError("Khoa_Code", "Mã này đã tồn tại");
                return View(model);
            }
            if (ModelState.IsValid)
            {
                Khoa khoa = new Khoa()
                {
                    Khoa_Code = model.Khoa_Code,
                    Khoa_Name = model.Khoa_Name
                };
                khoaService.Insert(khoa);
                khoaService.Save();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            Khoa khoa = khoaService.GetByID(Id);
            if (khoa is null)
            {
                return HttpNotFound();
            }
            EditKhoa objKhoa = new EditKhoa()
            {
                ID = khoa.ID,
                Khoa_Code = khoa.Khoa_Code,
                Khoa_Name = khoa.Khoa_Name
            };
            return View(objKhoa);
        }

        [HttpPost]
        public ActionResult Edit(EditKhoa modelKhoa)
        {
            if (ModelState.IsValid)
            {
                Khoa eKhoa = new Khoa()
                {
                    ID = modelKhoa.ID,
                    Khoa_Code = modelKhoa.Khoa_Code,
                    Khoa_Name = modelKhoa.Khoa_Name
                };
                khoaService.Update(eKhoa);
                khoaService.Save();
                return RedirectToAction("Index");
            }
            return View(modelKhoa);
        }

        [HttpGet]
        public ActionResult Detail(int Id)
        {
            Khoa khoa = khoaService.GetByID(Id);
            if (khoa is null)
            {
                return HttpNotFound();
            }
            Details deKhoa = new Details()
            {
                ID = khoa.ID,
                Khoa_Code = khoa.Khoa_Code,
                Khoa_Name = khoa.Khoa_Name
            };
            return View(deKhoa);
        }

        //[HttpPost]
        //public ActionResult Delete(int Id)
        //{
        //    Khoa khoa = khoaService.GetByID(Id);
        //    if(khoa is null)
        //    {
        //        return HttpNotFound();
        //    };
        //    khoaService.Delete(khoa);
        //    khoaService.Save();
        //    return RedirectToAction("Index");
        //}


        //ajax
        [HttpPost]
        public ActionResult Delete(int Id)
        {
            string messenger = "";
            bool success = false;
            Khoa khoa = khoaService.GetByID(Id);
            if (khoa is null)
            {
                messenger = "Id không tồn tại";
                success = false;
            }
            if (khoa.StudentOfKhoas.Count > 0)
            {
                messenger = "Sinh Viên Này Đã Tồn Tại";
                success = false;
            }
            else
            {
                khoaService.Delete(khoa);
                khoaService.Save();
                messenger = "Xóa Thành Công";
                success = true;
            }
            return Json(new { messenger = messenger, success = success }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult DeleteKhoaCode(string khoaCode)
        {
            string messenger = "";
            bool success = false;
            
         
            
                khoaService.DeleteKhoaCode(khoaCode);

                messenger = "Xóa Thành Công";
                success = true;
            
            return Json(new { messenger = messenger, success = success }, JsonRequestBehavior.AllowGet);
        }

    }

}

Views/Khoa/Create.cshtml
@model StudentManage.ViewModels.KhoaViewModel.CreateKhoa

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CreateKhoa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Khoa_Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Khoa_Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Khoa_Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Khoa_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Khoa_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Khoa_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Khoa/Detail.cshtml
@model StudentManage.ViewModels.KhoaViewModel.Details

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detail</h2>

<div>
    <h4>Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Khoa_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Khoa_Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Khoa_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Khoa_Name)
        </dd>

    </dl>

</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { Id = Model.ID}) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Khoa/Edit.cshtml
@model StudentManage.ViewModels.KhoaViewModel.EditKhoa

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>EditKhoa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Khoa_Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Khoa_Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Khoa_Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Khoa_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Khoa_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Khoa_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Khoa/Index.cshtml
@model IEnumerable<StudentManage.Models.Khoa>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
 <link href = "https://cdn.jsdelivr.net/npm/sweetalert2@9.17.1/dist/sweetalert2.min.css" rel = "stylesheet" >

<style>
    #but {
        margin-bottom: 20px;
    }
</style>
<h2>Danh sách khoa học</h2>

<a href="/Khoa/Create" class="btn btn-success" id="but">Them Khoa</a>

<table class="table table-dark table-striped">
    <thead>
        <tr>

            <th style="width: 10%;"> Ma Khoa </th>
            <th style="width: 50%;"> Ten Khoa </th>
            <th style="width: 20%;"> Action </th>

        </tr>
    </thead>
    <tbody>
        @if (Model.Count() >= 0)
        {
            foreach (var itemk in Model)
            {
                <tr>

                    <td>@itemk.Khoa_Code</td>
                    <td>@itemk.Khoa_Name</td>

                    <td>
                        <a class="btn btn-info" href="/Khoa/Edit/@itemk.ID">Sửa</a>
                        <a class="btn btn-warning" href="/Khoa/Detail/@itemk.ID">Chi Tiết</a>
                        @*@using (Html.BeginForm("Delete", "Khoa", new { Id = itemk.ID }, FormMethod.Post))
        {
            <button class="btn btn-danger btnDelete" data-id="@itemk.ID">Xóa</button>
        }*@
                        <button class="btn btn-danger btnDelete" data-id="@itemk.ID">Xóa</button>
                        <button class="btn btn-success btnDeleteK" data-string="@itemk.Khoa_Code">Xóa Theo Khoa Code</button>

                    </td>
                </tr>
            }
        }
    </tbody>

</table>
@section Scripts{
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9.17.1/dist/sweetalert2.min.js"></script>
    <script type="text/javascript">


    //////// query
    $('.btnDelete').click(function () {
    var id = $(this).attr("data-id");
        Swal.fire({
            title: 'Muốn Xóa Thiệt Hả !',
            text: "Không Thể Hoàn Tác !",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Ok, Xóa'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("Delete", "Khoa")",
                    data: {
                        Id: id
                    }
                }).done(function (reponse) {
                    if (reponse.success) {
                        Swal.fire(
                            'Deleted!',
                            reponse.messenger,
                            'success'
                        )
                        location.reload();
                    }
                    else {
                        Swal.fire(reponse.messenger);
                    }
                }).fail(function () {
                    alert("ERROR, Vui lòng quay lại sau")
                })
            }
        })
    });

          $('.btnDeleteK').click(function () {
            var khoaCodee = $(this).attr("data-string");
            var tb = confirm("Bạn có muốn xóa");
            if (tb) {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("DeleteKhoaCode", "Khoa")",
                    data: {
                        khoaCode: khoaCodee
                    }
                }).done(function (reponse) {
                    if (reponse.success) {
                        alert(reponse.messenger);
                        location.reload();
                    }
                       // else {
                    //    alert(reponse.messenge);
                    //}

                }).fail(function () {
                    alert("ERROR, Vui lòng quay lại sau")
                })
            }

        });
    </script>
}